# Generated by Django 5.2.1 on 2025-05-23 07:34

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='matatu',
            old_name='plate_number',
            new_name='number_plate',
        ),
        migrations.RenameField(
            model_name='matatu',
            old_name='capacity',
            new_name='seater_capacity',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='end_location',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='name',
            new_name='highway_used',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='start_location',
            new_name='origin',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='status',
        ),
        migrations.RemoveField(
            model_name='matatu',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='matatu',
            name='status',
        ),
        migrations.RemoveField(
            model_name='route',
            name='base_fare',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='sacco',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sacco',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='sacco',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_matatu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_driver', to='core.matatu'),
        ),
        migrations.AddField(
            model_name='driver',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 1, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='national_id',
            field=models.CharField(default=' ', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='matatu',
            name='car_id',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matatu',
            name='condition',
            field=models.CharField(default='Good', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matatu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matatu',
            name='is_insured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matatu',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.route'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_name',
            field=models.CharField(default='Thika superhighway', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sacco',
            name='contact',
            field=models.CharField(default='0112005718', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sacco',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sacco',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saccos', to='core.route'),
        ),
        migrations.AddField(
            model_name='sacco',
            name='services_offered',
            field=models.TextField(default='Not specified'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sacco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.sacco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favourite_saccos', models.ManyToManyField(related_name='favourited_by', to='core.sacco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JourneyQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('TO_DESTINATION', 'Nairobi → Destination'), ('TO_NAIROBI', 'Destination → Nairobi')], max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('queue_position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matatu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='core.matatu')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.sacco')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.sacco')),
            ],
        ),
        migrations.AddField(
            model_name='matatu',
            name='current_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stage'),
        ),
        migrations.AddField(
            model_name='sacco',
            name='stages',
            field=models.ManyToManyField(related_name='operating_saccos', to='core.stage'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matatu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.matatu')),
            ],
            options={
                'unique_together': {('matatu', 'seat_number')},
            },
        ),
    ]
