# Generated by Django 5.2.1 on 2025-05-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stage_rename_plate_number_matatu_number_plate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
